framework:
  messenger:
    failure_transport: failed

    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          stream: 'user_creation_stream'
          group: 'user_creators'
          consumer: 'consumer'
          auto_setup: true
          delete_after_ack: true

        retry_strategy:
          max_retries: 3
          delay: 1000
          multiplier: 2
          max_delay: 10000

      failed: 'doctrine://default?queue_name=failed'

    default_bus: messenger.bus.default

    buses:
       messenger.bus.default: []

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async

      'App\Messenger\Message\UserMessage': async